# Generated by Django 3.0.7 on 2021-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='Subject_name',
        ),
        migrations.AddField(
            model_name='course',
            name='Class_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Course_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Duration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
