# Generated by Django 3.1.7 on 2021-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210919_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Networking', 'Networking')], max_length=100, null=True),
        ),
    ]
