# Generated by Django 3.0.7 on 2021-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
