# Generated by Django 3.0.7 on 2021-11-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211106_0030'),
        ('learning', '0004_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.Teacher'),
        ),
    ]
