# Generated by Django 3.0.7 on 2021-09-18 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210918_1738'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='learning.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(70)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
