# Generated by Django 3.1.7 on 2021-09-30 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(70)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
