# Generated by Django 3.1.7 on 2021-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_course_tag'),
        ('accounts', '0006_auto_20211026_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='learning.Course'),
        ),
    ]
