# Generated by Django 3.0.7 on 2021-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_courseorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (3, 'PENDING'), (2, 'FAILURE')], default=3),
        ),
    ]
