# Generated by Django 3.0.7 on 2021-11-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211103_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(3, 'PENDING'), (2, 'FAILURE'), (1, 'SUCCESS')], default=3),
        ),
    ]
