# Generated by Django 3.0.7 on 2021-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211106_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(2, 'FAILURE'), (3, 'PENDING'), (1, 'SUCCESS')], default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
